// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>
using Network.RMI_Common.RMI_ParsingClasses;
using System.Collections.Generic;
using System;


namespace Network.RMI_Common.RMI_ParsingClasses
{

using global::System;
using global::FlatBuffers;

public struct flat_sendTestDataToServer : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static flat_sendTestDataToServer GetRootAsflat_sendTestDataToServer(ByteBuffer _bb) { return GetRootAsflat_sendTestDataToServer(_bb, new flat_sendTestDataToServer()); }
  public static flat_sendTestDataToServer GetRootAsflat_sendTestDataToServer(ByteBuffer _bb, flat_sendTestDataToServer obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p.bb_pos = _i; __p.bb = _bb; }
  public flat_sendTestDataToServer __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public float TimeData { get { int o = __p.__offset(4); return o != 0 ? __p.bb.GetFloat(o + __p.bb_pos) : (float)0.0f; } }
  public string TestData { get { int o = __p.__offset(6); return o != 0 ? __p.__string(o + __p.bb_pos) : null; } }
#if ENABLE_SPAN_T
  public Span<byte> GetTestDataBytes() { return __p.__vector_as_span(6); }
#else
  public ArraySegment<byte>? GetTestDataBytes() { return __p.__vector_as_arraysegment(6); }
#endif
  public byte[] GetTestDataArray() { return __p.__vector_as_array<byte>(6); }

  public static Offset<flat_sendTestDataToServer> Createflat_sendTestDataToServer(FlatBufferBuilder builder,
      float timeData = 0.0f,
      StringOffset testDataOffset = default(StringOffset)) {
    builder.StartObject(2);
    flat_sendTestDataToServer.AddTestData(builder, testDataOffset);
    flat_sendTestDataToServer.AddTimeData(builder, timeData);
    return flat_sendTestDataToServer.Endflat_sendTestDataToServer(builder);
  }

  public static void Startflat_sendTestDataToServer(FlatBufferBuilder builder) { builder.StartObject(2); }
  public static void AddTimeData(FlatBufferBuilder builder, float timeData) { builder.AddFloat(0, timeData, 0.0f); }
  public static void AddTestData(FlatBufferBuilder builder, StringOffset testDataOffset) { builder.AddOffset(1, testDataOffset.Value, 0); }
  public static Offset<flat_sendTestDataToServer> Endflat_sendTestDataToServer(FlatBufferBuilder builder) {
    int o = builder.EndObject();
    return new Offset<flat_sendTestDataToServer>(o);
  }
    public static Offset<flat_sendTestDataToServer> Createflat_sendTestDataToServer(FlatBufferBuilder builder,
 sendTestDataToServer data) {
        var testDataOffset = builder.CreateString(data.testData);
        return Createflat_sendTestDataToServer(builder , data.timeData, testDataOffset);
    }

    public static byte[] Createflat_sendTestDataToServer(sendTestDataToServer data) {
        FlatBufferBuilder fbb = new FlatBufferBuilder(512);
        fbb.Finish(flat_sendTestDataToServer.Createflat_sendTestDataToServer(fbb, data).Value);
        byte[] result = fbb.SizedByteArray();
        fbb = null;
        return result;
    }

    public static sendTestDataToServer GetRootAsflat_sendTestDataToServer(byte[] data) {
        return new sendTestDataToServer(flat_sendTestDataToServer.GetRootAsflat_sendTestDataToServer( new ByteBuffer(data) ) );
    }

}};