// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace Network.RMI_Common.RMI_ParsingClasses
{

public enum RMI_PacketType : short
{
 pingCheck_Request = 1,
 heartBeatCheck_Request = 2,
 sendTestDataToServer = 3,
 sendTestDataToServer2 = 4,
 pingCheck_Response = 5,
 heartBeatCheck_Response = 6,
 sendTestDataToClient = 7,
 sendTestDataToClient2 = 8,
};


}
