// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>
using Network.RMI_Common.RMI_ParsingClasses;
using FlatBuffers;
using System.Collections.Generic;
using System;


namespace Network.RMI_Common.RMI_ParsingClasses
{

using global::System;
using global::FlatBuffers;

public struct flat_RMI_ProtocolVersionCheck : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static flat_RMI_ProtocolVersionCheck GetRootAsflat_RMI_ProtocolVersionCheck(ByteBuffer _bb) { return GetRootAsflat_RMI_ProtocolVersionCheck(_bb, new flat_RMI_ProtocolVersionCheck()); }
  public static flat_RMI_ProtocolVersionCheck GetRootAsflat_RMI_ProtocolVersionCheck(ByteBuffer _bb, flat_RMI_ProtocolVersionCheck obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p.bb_pos = _i; __p.bb = _bb; }
  public flat_RMI_ProtocolVersionCheck __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public int RmiProtocolVersion { get { int o = __p.__offset(4); return o != 0 ? __p.bb.GetInt(o + __p.bb_pos) : (int)0; } }

  public static Offset<flat_RMI_ProtocolVersionCheck> Createflat_RMI_ProtocolVersionCheck(FlatBufferBuilder builder,
      int rmi_protocol_version = 0) {
    builder.StartObject(1);
    flat_RMI_ProtocolVersionCheck.AddRmiProtocolVersion(builder, rmi_protocol_version);
    return flat_RMI_ProtocolVersionCheck.Endflat_RMI_ProtocolVersionCheck(builder);
  }

  public static void Startflat_RMI_ProtocolVersionCheck(FlatBufferBuilder builder) { builder.StartObject(1); }
  public static void AddRmiProtocolVersion(FlatBufferBuilder builder, int rmiProtocolVersion) { builder.AddInt(0, rmiProtocolVersion, 0); }
  public static Offset<flat_RMI_ProtocolVersionCheck> Endflat_RMI_ProtocolVersionCheck(FlatBufferBuilder builder) {
    int o = builder.EndObject();
    return new Offset<flat_RMI_ProtocolVersionCheck>(o);
  }
    public static Offset<flat_RMI_ProtocolVersionCheck> Createflat_RMI_ProtocolVersionCheck(FlatBufferBuilder builder,
 RMI_ProtocolVersionCheck data) {
        return Createflat_RMI_ProtocolVersionCheck(builder , data.rmi_protocol_version);
    }

    public static byte[] Createflat_RMI_ProtocolVersionCheck(RMI_ProtocolVersionCheck data) {
        FlatBufferBuilder fbb = new FlatBufferBuilder(512); 
        fbb.Finish(flat_RMI_ProtocolVersionCheck.Createflat_RMI_ProtocolVersionCheck(fbb, data).Value);
        byte[] result = fbb.SizedByteArray();
        fbb = null;
        return result;
    }

    public static RMI_ProtocolVersionCheck GetRootAsflat_RMI_ProtocolVersionCheck(byte[] data) {
        return new RMI_ProtocolVersionCheck(flat_RMI_ProtocolVersionCheck.GetRootAsflat_RMI_ProtocolVersionCheck( new ByteBuffer(data) ) );
    }
}};