// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>
using Network.RMI_Common.RMI_ParsingClasses;
using FlatBuffers;
using System.Collections.Generic;
using System;


namespace Network.RMI_Common.RMI_ParsingClasses
{

using global::System;
using global::FlatBuffers;

public struct flat_RMI_UDP_ConnectionConfirm : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static flat_RMI_UDP_ConnectionConfirm GetRootAsflat_RMI_UDP_ConnectionConfirm(ByteBuffer _bb) { return GetRootAsflat_RMI_UDP_ConnectionConfirm(_bb, new flat_RMI_UDP_ConnectionConfirm()); }
  public static flat_RMI_UDP_ConnectionConfirm GetRootAsflat_RMI_UDP_ConnectionConfirm(ByteBuffer _bb, flat_RMI_UDP_ConnectionConfirm obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p.bb_pos = _i; __p.bb = _bb; }
  public flat_RMI_UDP_ConnectionConfirm __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public int CheckUDPConnection { get { int o = __p.__offset(4); return o != 0 ? __p.bb.GetInt(o + __p.bb_pos) : (int)0; } }

  public static Offset<flat_RMI_UDP_ConnectionConfirm> Createflat_RMI_UDP_ConnectionConfirm(FlatBufferBuilder builder,
      int checkUDP_Connection = 0) {
    builder.StartObject(1);
    flat_RMI_UDP_ConnectionConfirm.AddCheckUDPConnection(builder, checkUDP_Connection);
    return flat_RMI_UDP_ConnectionConfirm.Endflat_RMI_UDP_ConnectionConfirm(builder);
  }

  public static void Startflat_RMI_UDP_ConnectionConfirm(FlatBufferBuilder builder) { builder.StartObject(1); }
  public static void AddCheckUDPConnection(FlatBufferBuilder builder, int checkUDPConnection) { builder.AddInt(0, checkUDPConnection, 0); }
  public static Offset<flat_RMI_UDP_ConnectionConfirm> Endflat_RMI_UDP_ConnectionConfirm(FlatBufferBuilder builder) {
    int o = builder.EndObject();
    return new Offset<flat_RMI_UDP_ConnectionConfirm>(o);
  }
    public static Offset<flat_RMI_UDP_ConnectionConfirm> Createflat_RMI_UDP_ConnectionConfirm(FlatBufferBuilder builder,
 RMI_UDP_ConnectionConfirm data) {
        return Createflat_RMI_UDP_ConnectionConfirm(builder , data.checkUDP_Connection);
    }

    public static byte[] Createflat_RMI_UDP_ConnectionConfirm(RMI_UDP_ConnectionConfirm data) {
        FlatBufferBuilder fbb = new FlatBufferBuilder(512);
        fbb.Finish(flat_RMI_UDP_ConnectionConfirm.Createflat_RMI_UDP_ConnectionConfirm(fbb, data).Value);
        byte[] result = fbb.SizedByteArray();
        fbb = null;
        return result;
    }

    public static RMI_UDP_ConnectionConfirm GetRootAsflat_RMI_UDP_ConnectionConfirm(byte[] data) {
        return new RMI_UDP_ConnectionConfirm(flat_RMI_UDP_ConnectionConfirm.GetRootAsflat_RMI_UDP_ConnectionConfirm( new ByteBuffer(data) ) );
    }
}};